
services:
  app:
    build: .
    ports:
      - '9000:9000'  
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    environment:
      MONGODB_URI: mongodb://mongodb:27017  
      REDIS_URL: redis://redis:6379 
      RABBITMQ_URL: amqp://rabbitmq:5672

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - '15672:15672'  # RabbitMQ
      - '5672:5672'    # RabbitMQ default port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongodb_data:
